version: '3'
services:
  mongo_db:
    image: mongo
    container_name: mongoDB
    restart: always
    ports:
      - 27017:27017

  internal1-container:
    image: bugscleaners/internal1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    restart: always

    depends_on:
      - mongo_db

  internal2-container:
    image: bugscleaners/internal2
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always

